SITE:
    Local: '127.0.0.1:8888'
    Remote:
        Url: 'https://hcr.researchspaces.ca/'
        Path: '/user'
PORT: 8000
BSREWRITE:
    Css:
        Match: "/themes/hcrc_d8_theme/css/"
        Replace: "/css/"
    Js:
        Match: "/themes/hcrc_d8_theme/js/"
        Replace: "/js/"
PATHS:
    Watch:
      #changes in these compiled files trigged reload
      - ./css/*.css
      - ./js/*.js
    Scss:
        Dir: css/src
        #FileName: app.scss
        Libraries:
            - node_modules/gerillass/scss
            #- css/libraries/typeplate
    Css:
        Dir: css
        #FileName: app.css
    Js:
        Src: ./js/src/*.js
        Dest: js
        FileName: 'hcrc.js'
    Img:
        Src: img/src
        Dest: img

